# THIS FILE IS AUTO-GENERATED BY THE `util/boards` SCRIPT FROM THE BASE
# DIRECTORY, DO NOT EDIT THIS FILE BUT EDIT THE SCRIPT ITSELF AND THEN
# PIPE THE OUTPUT TO THIS FILE.

__all__ = ['boards', 'all_boards']

boards = [
      '3',    'a',  'aco',   'adv',  'an',
    'asp',  'biz',    'c',   'cgl',  'ck',
     'cm',   'co',    'd',   'diy',   'e',
      'f',   'fa',  'fit',     'g',  'gd',
    'gif',    'h',   'hc',   'his',  'hm',
     'hr',    'i',   'ic',   'int',  'jp',
      'k', 'lgbt',  'lit',     'm', 'mlp',
     'mu',    'n', 'news',     'o', 'out',
      'p',   'po',  'pol',    'qa', 'qst',
      'r',  'r9k',    's',   'sci',  'sp',
      't',   'tg',  'toy', 'trash', 'trv',
     'tv',    'u',    'v',    'vg',  'vp',
     'vr',    'w',   'wg',   'wsg', 'wsr',
      'x',    'y'
]

all_boards = [
      '3',     'a',  'aco',  'adv',  'an',
    'asp',     'b',  'biz',    'c', 'cgl',
     'ck',    'cm',   'co',    'd', 'diy',
      'e',     'f',   'fa',  'fit',   'g',
     'gd',   'gif',    'h',   'hc', 'his',
     'hm',    'hr',    'i',   'ic', 'int',
     'jp',     'k', 'lgbt',  'lit',   'm',
    'mlp',    'mu',    'n', 'news',   'o',
    'out',     'p',   'po',  'pol',  'qa',
    'qst',     'r',  'r9k',    's', 's4s',
    'sci',   'soc',   'sp',    't',  'tg',
    'toy', 'trash',  'trv',   'tv',   'u',
      'v',    'vg',   'vp',   'vr',   'w',
     'wg',   'wsg',  'wsr',    'x',   'y'
]
